### ISSUE TITLE
Add function: genSecret

### ISSUE THREAD

**Issue by Gavin1937** [Gavin1937/MedReminder-backend#19]
**put this function into class Utilities**

**pack under cs3337.MedReminder.Util**

* public static String genSecret(Integer length = 32)
  * generate a String length defined by **"length"** with **lower case letter**, **upper case letter**, and **numbers**
  * this String should be generated with an uniform distribution random number generation algorithm
    * simply use [nextInt](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextInt-int-) in java Random library
  * Param: **length** is set to 32 by default
    * use function overloading for that
    * have two genSecret functions, one with length param and one without
    * the one without param will automatically set length = 32
  * return that generated String
* After you finish this function, you should uncomment [genSecretTest function in UtilitiesTests.java](https://github.com/Gavin1937/MedReminder-backend/blob/main/src/test/java/cs3337/MedReminderbackend/UtilitiesTests.java) for unit testing

**Comment by Gavin1937** [comment]
make sure to make this function & the whole Utilities class static

**Comment by basnetaakash23** [comment]
@Gavin1937 Let me work on this and get started on this project.

**Comment by Gavin1937** [comment]
@basnetaakash23 
Really appreciate for your participation! However, I can't let you work on this project because it is a project for my school.
I saw you already forked this project, you can work on your fork if you're still interesting about it.
If you need any help on the overall concept of the project, I am glad to explain them to you!

**Comment by basnetaakash23** [comment]
Sure! @Gavin1937 You can explain to me this project. Also once you submit this project, we can work on it to further expand this.
