### ISSUE TITLE
Add model class Doctors

### ISSUE THREAD

**Issue by Gavin1937** [Gavin1937/MedReminder-backend#9]
This class holds all the doctor information

* it contains following private members
  * Integer id
  * String fname
  * String lname
  * String phone
  * String email
* also add dedicate getters for all of them
* **you shouldn't add any setters in this model class**
  * because we shouldn't edit hospital db

**Comment by Gavin1937** [comment]
Pack this class under cs3337.MedReminder.Model

**Comment by Gavin1937** [comment]
also add these two functions
* public JSONObject toJson() convert the whole obj to json object
* public void fromJson(JSONObject json) set values to all members from json object

**Comment by Gavin1937** [comment]
make sure we can use a constructor to assign values to all the private members at once

**Comment by Bigluis007** [comment]
@Gavin1937 I'll take care of this one my g
